name: PR Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: read

jobs:
  validate-pr:
    uses: cert-study-dev/unified-reusable-workflow/.github/workflows/conventional-commit.yml@main